language: node_js
node_js:
  - "0.10"
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libzmq3-dev libpcre3-dev julia -y
  - julia -e 'Pkg.add("ZMQ"); Pkg.add("FactCheck")'
